### ISSUE TITLE
[Feature Request] Use sortBy parameters in Index operation

### ISSUE THREAD

**Issue by Gounlaf** [tailflow/laravel-orion#109]
Hi,

It would be nice to be able to use the "sortBy" parameters (or any other) in the "Index" operation.
I might be able to create a PR for that.

Thanks,

Regards.

**Comment by alexzarbn** [comment]
Hi @Gounlaf,

What is the use case for that versus just using the search endpoint?

**Comment by Gounlaf** [comment]
Hi @alexzarbn,

`list/index` endpoint is, in my usage of APIs, a standard need, with usually sorting on "date" (created/updated) or "sequences" (id) attributes.

When I wrote the issue I thank `search` was overkill.

Now, with `search` having so much capabilities, I'm wondering: what the purpose of the `index`, if `search` does the same thing ? :open_mouth:

**Comment by alexzarbn** [comment]
@Gounlaf 

The purpose of the `index` endpoint is to provide a simple _and standard in terms of CRUD terminology_ way for listing paginated resources. However, in a more complex API architectures, it is advised to use `search` all the time (especially, if an API is used purely as SPAs backend), because sooner or later there will be a need for filtering or sorting.

For now, I do not think that making the `index` endpoint work with sorting or filtering is a right thing to do, as it may bring even more confusion on why there are two similar endpoints and which one to use in a particular scenario.
