### ISSUE TITLE
Aggregate support: count, max, min, avg, sum

### ISSUE THREAD

**Issue by olragon** [tailflow/laravel-orion#127]
Can we implement this feature?

Thank you for your great project.

**Comment by GautierDele** [comment]
Would be necessary for us :)

**Comment by GautierDele** [comment]
In my opinion we should add a new params "includesCount", "includesMax", etc and those counts should be directly added to the resources because you might want to count the number of children for each resource. The problem is: what if you want to add params to those avg / count / etc because you might want to filter what you include / etc ? This could be added in the direct close of "withCount" pretty easily ?

I don't think we can add this to the meta since this should be dynamic to each resource ?

**Comment by jasper-ter-veen** [comment]
It could be similar to the search endpoint. But maybe called `/aggregates`
```
{
  "aggregates": [
    {"field": "amount", "type": "sum"}, 
    {"field": "related.score", "type": "avg"}, 
    {"field": "related.score", "type": "max", "alias" : "maxScore" } 
  ], 
  "filters" : [.... ], 
 ... 
} 
```

Besides the field, type and alias properties you could add a format, or max_decimals. 


Response:
```
{
  "data" : {
    "amount" : 12,
    "score": 34.089, 
    "maxScore": 87.3
  }, 
  "meta": {} 
} 
```

An alternative is to include this into the search endpoint and respond with an aggregates section next to the data section in the response.

**Comment by alexzarbn** [comment]
Hi @jasper-ter-veen,

The proposal looks really nice! It definitely covers more advanced use cases, however, similar to the PR #183, there is a problem with such approach when you would need to retrieve aggregates of one particular entity (basically making a request to the `show` endpoint).

I think it might be worth implementing both an advanced and a simple version of this feature. The advanced one would be using the `search` endpoint with `aggregates` parameter, like both @GautierDele and @jasper-ter-veen suggested. The simple one would be using `with_count`, `with_max`, etc. query parameters on endpoints like `show`, `store`, etc. without any filters.

**Comment by GautierDele** [comment]
I think its a good idea, give me some time incrementing the PR to allow both and push the limit of the search endpoint to allow filtering on aggregates
