### ISSUE TITLE
Missing parent entity authorization in Relation*-Controllers

### ISSUE THREAD

**Issue by horstoeko** [tailflow/laravel-orion#133]
Hi,

I think that I have found a bug. Some methods in the HandlesRelation*-Traits do not authorise the parent entity. This does not seem correct to me. What is your opinion? 

I noticed this in HandlesRelationStandardOperations->store. It does not check if the logged in user has at least read permissions on the parent entity. However, the "index" method performs a check for read permissions on the parent entity (completely correctly, in my view).

**Comment by alexzarbn** [comment]
Hi @horstoeko,

That's a good question! The `index` method checks parent entity permissions simply because there is no single child entity to check against. 

The same applies to the `store` method, however, it is a bit tricky - what does `store` operation on a child entity mean to the parent entity in terms of permissions - is it an update or a view? In some cases, a user may be able to read the parent entity, but not update it. In other (rare, however) cases, a user may not have any access to the parent entity, yet would have the ability to work with its child entities. Due to that discrepancy and possible confusion it was decided to omit parent entity permissions checks in the `store` operation.

As for the other operations, since there is an actual entity available, all the logic goes into the relevant `Policy` class.

What are the benefits do you see in implementing the permissions check on the parent entity in all operations?

**Comment by marcvdm** [comment]
I made a draft pull request for this. We currently use this package for several packages and this is something we really need.
[#135 ](https://github.com/tailflow/laravel-orion/pull/135)

**Comment by horstoeko** [comment]
Hi @alexzarbn

Thanks for your statement. I can follow your (very good) explanations and understand the problems. Probably the solution of pull request #135 is exactly where I wanted to go. Let's construct a (theoretical) case:

I have serveral blog categories to which of course different posts belong. The blog categories have users assigned to them, who can read entries in the respective categories and create/edit them if necessary. I must now be able to avoid that non-authorized users can read/edit posts for a category.

But now I think that (as I said) the pull request #135 already goes in the right direction.
